#!/bin/bash

# eval "$(starship init bash)"
function _update_ps1() {
    PS1=$(powerline-shell $?)
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

eval "$(direnv hook bash)"

alias l='lsd'
alias la='ls -a'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias cat='batcat'

alias dive="docker run -ti --rm  -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive"

#some docker alias
alias dokill='docker kill `docker ps -q`'
alias dormall='docker rm `docker ps -qa`'
alias doco='docker compose'
alias ctop='docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro quay.io/vektorlab/ctop:latest'
alias lzd='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /home/amorale/.lazydocker_config:/.config/jesseduffield/lazydocker lazyteam/lazydocker'
alias nvitop="pipx run nvitop"

source "$HOME/.local/share/blesh/ble.sh"
